# config.yaml

# Словарь категорий навыков
skill_categories:
  Programming Languages:
    - Python
    - Java
    - C++
    - C#
    - JavaScript
    - TypeScript
    - PHP
    - Go
    - Ruby
    - Swift
    - Kotlin
    - Rust
    - Scala
    - Perl

  Web Frameworks:
    - HTML
    - CSS
    - JavaScript
    - React
    - Angular
    - Vue.js
    - Django
    - Flask
    - Spring
    - .NET Core
    - Laravel
    - Express
    - Node.js
    - Next.js
    - Nuxt.js
    - Svelte

  Databases:
    - SQL
    - MySQL
    - PostgreSQL
    - SQLite
    - Oracle
    - MongoDB
    - Redis
    - Cassandra
    - Firebase
    - MariaDB

  Version Control & DevOps:
    - Git
    - GitHub
    - GitLab
    - SVN
    - Docker
    - Kubernetes
    - Jenkins
    - CI/CD
    - Bash
    - Linux
    - GitHub Actions
    - Azure DevOps

  Cloud Platforms:
    - AWS
    - Azure
    - Google Cloud
    - Heroku
    - DigitalOcean
    - Yandex.Cloud

  Data & ML:
    - Pandas
    - NumPy
    - TensorFlow
    - PyTorch
    - Scikit-learn
    - Jupyter
    - Keras
    - OpenCV
    - NLTK
    - SpaCy

  IT Practices:
    - OOP
    - REST API
    - Microservices
    - Agile
    - Scrum
    - Kanban
    - TDD
    - Unit Testing
    - BDD
    - CI/CD

  Action Verbs:
    - Developed
    - Разработал
    - Разработала
    - Разрабатывал
    - Designed
    - Спроектировал
    - Спроектировала
    - Проектировал
    - Implemented
    - Внедрил
    - Внедрила
    - Внедрял
    - Architected
    - Спроектировал архитектуру
    - Coded
    - Закодировал
    - Кодировал
    - Programmed
    - Запрограммировал
    - Программировал
    - Debugged
    - Отладил
    - Отлаживал
    - Fixed bugs
    - Исправил ошибки
    - Tested
    - Протестировал
    - Тестировал
    - Validated
    - Валидировал
    - Deployed
    - Развернул
    - Развертывал
    - Released
    - Выпустил
    - Релизнул
    - Configured
    - Настроил
    - Настраивал
    - Integrated
    - Интегрировал
    - Интегрировала
    - Migrated
    - Мигрировал
    - Мигрировала
    - Populated database
    - Пополнил базу
    - Пополнила базу
    - Optimized queries
    - Оптимизировал запросы
    - Designed schema
    - Спроектировал схему БД
    - Maintained database
    - Поддерживал базу данных
    - Analyzed data
    - Проанализировал данные
    - Проанализировала данные
    - Collected data
    - Собрал данные
    - Собрала данные
    - Optimized
    - Оптимизировал
    - Оптимизировала
    - Refactored
    - Рефакторил
    - Рефакторила
    - Documented
    - Задокументировал
    - Задокументировала
    - Wrote documentation
    - Написал документацию
    - Написала документацию
    - Managed
    - Управлял
    - Управляла
    - Coordinated
    - Координировал
    - Координировала
    - Led
    - Вёл проект
    - Вела проект
    - Maintained
    - Поддерживал
    - Поддерживала
    - Supported
    - Сопровождал
    - Сопровождала

  Soft Skills:
    - Communication
    - Коммуникация
    - Общение
    - Коммуникативный
    - Коммуникабельный
    - Teamwork
    - Team Work
    - Работа в команде
    - Командная работа
    - Team-oriented
    - Team oriented
    - Командный
    - Командный игрок
    - Problem Solving
    - Решение проблем
    - Навыки решения проблем
    - Problem-solving
    - Проблемно-ориентированный
    - Critical Thinking
    - Критическое мышление
    - Критически мыслящий
    - Adaptability
    - Адаптивность
    - Гибкость
    - Adaptable
    - Адаптивный
    - Гибкий
    - Self-Learning
    - Самообучение
    - Способность к самообучению
    - Self-learning
    - Самообучающийся
    - Time Management
    - Тайм-менеджмент
    - Управление временем
    - Time-management
    - Организованный
    - Умеющий планировать время
    - Creativity
    - Креативность
    - Creative
    - Креативный
    - Collaboration
    - Сотрудничество
    - Коллаборация
    - Collaborative
    - Сотрудничающий
    - Коллаборативный
    - Emotional Intelligence
    - Эмоциональный интеллект
    - EQ
    - Emotionally intelligent
    - Эмоционально интеллигентный
    - Эмоционально интеллектуальный
    - Resilience
    - Устойчивость
    - Стрессоустойчивость
    - Resilient
    - Устойчивый
    - Стойкий
    - Growth Mindset
    - Установка на рост
    - Ориентированный на рост
    - Growth-minded
    - Рост-ориентированный
    - Remote Work
    - Удалённая работа
    - Дистанционная работа
    - Remote-working
    - Удалённо работающий
    - Работа на удалёнке
    - Digital Literacy
    - Цифровая грамотность
    - Digitally literate
    - Грамотный в цифровых технологиях
    - Цифрово грамотный

# Ключевые слова для оценки
keywords:
  - Python
  - Machine Learning
  - NLP
  - SQL
  - Deep Learning

# Веса для итогового score
weights:
  kw: 0.5
  skills: 0.2
  errors: 0.3
